### ISSUE TITLE
ClientIdGenerator Obsolete?

### ISSUE THREAD

**Issue by basz** [zf-fr/zfr-oauth2-server-doctrine#4]
Isn't this obsolete https://github.com/basz/zfr-oauth2-server-doctrine/blob/wip/src/Id/ClientIdGenerator.php

**Comment by bakura10** [comment]
Yes it is if we generate the ID on our end.

I don't remember how you did create it in the Client. Maybe we could use that: https://github.com/ramsey/uuid ?

**Comment by basz** [comment]
hm, I now sort of see what this does... it is a public method on the ClientService.

[uuid](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Id/UuidGenerator.php) is now build into doctrine, would work for me, ramsey/uuid not needed :-) unless see [WARNING](http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_uuid).

**Comment by bakura10** [comment]
Well, actually I suppose the client generation ID should be moved in the Client constructor :).

**Comment by basz** [comment]
yep agreed.
