### ISSUE TITLE
proxy aren't compatible with accessor return types

### ISSUE THREAD

**Issue by basz** [zf-fr/zfr-oauth2-server-doctrine#5]
proxy aren't compatible with accessor return types on entities until doctrine-orm-module and/or doctrine-module allow for doctrine/common 2.6.

requiring  "doctrine/common": "2.6.1 as 2.5.4" seems to solve the issue for now. I did this in my project composer.json. What do you think, should we include that in this composer.json

https://gist.github.com/basz/1b25ab8843f905547363
https://github.com/doctrine/doctrine2/issues/4884

**Comment by basz** [comment]
but, ... This makes me happy 

?access_token=3bb6ebace406a924eed88890eddb5936e53761c6
{"error":"Access token has expired or has been deleted"}

**Comment by bakura10** [comment]
So it's working? Nice :p. It'll be even better with support for JWT token :p

**Comment by basz** [comment]
does those JWT Tokens have anything to do with the session token https://github.com/Ocramius/PSR7Session are using?

**Comment by bakura10** [comment]
Kinda. It's just a different type of access token. But we don't need to use this library. But forget that, I've already used JWT so i may do it once everything else has been updated :)
